### ISSUE TITLE
Example in readme does not work

### ISSUE THREAD

**Issue by Equim-chan** [bytecodealliance/wit-bindgen#649]
wit/host.wit
```
package example:host

world host {
  import print: func(msg: string)

  export run: func()
}
```

src/lib.rs
```rust
wit_bindgen::generate!("host");
```

Cargo.toml
```toml
[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = { git = "https://github.com/bytecodealliance/wit-bindgen", version = "0.10.0" }
```

Error message
```plaintext
error: export parameter required for `world`
 --> wasi-wit/src/lib.rs:1:1
  |
1 | wit_bindgen::generate!("host");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the macro `wit_bindgen::generate` (in Nightly builds, run with -Z macro-backtrace for more info)

```

**Comment by Mossaka** [comment]
Did you add `export_host!(MyHost);` to `src/lib.rs`?

**Comment by Equim-chan** [comment]
It doesn't matter because the error is in the first line. Even if I add the whole thing the error will persist.

src/lib.rs
```rust
// Use a procedural macro to generate bindings for the world we specified in
// `host.wit`
wit_bindgen::generate!("host");

// Define a custom type and implement the generated `Host` trait for it which
// represents implementing all the necessary exported interfaces for this
// component.
struct MyHost;

impl Host for MyHost {
    fn run() {
        print("Hello, world!");
    }
}

// The following macro is generated by wit-bindgen and is always named `export_{world_name}`
export_host!(MyHost);
```

```shell
$ cargo build --target wasm32-wasi
error: export parameter required for `world`
 --> src/lib.rs:3:1
  |
3 | wit_bindgen::generate!("host");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the macro `wit_bindgen::generate` (in Nightly builds, run with -Z macro-backtrace for more info)

error: cannot find macro `export_host` in this scope
  --> src/lib.rs:17:1
   |
17 | export_host!(MyHost);
   | ^^^^^^^^^^^

error[E0405]: cannot find trait `Host` in this scope
  --> src/lib.rs:10:6
   |
10 | impl Host for MyHost {
   |      ^^^^ not found in this scope

error[E0423]: expected function, found macro `print`
  --> src/lib.rs:12:9
   |
12 |         print("Hello, world!");
   |         ^^^^^ not a function
   |
help: use `!` to invoke the macro
   |
12 |         print!("Hello, world!");
   |              +

Some errors have detailed explanations: E0405, E0423.
For more information about an error, try `rustc --explain E0405`.
error: could not compile `wasi-wit` (lib) due to 4 previous errors
```

**Comment by LLFourn** [comment]
It looks like the macro invocation of the type:

```
wit_bindgen::generate!("host");
```

was broken in #604. There is no `export_{}` macro exported anymore. Taking a random example, you have to do something like: https://github.com/bytecodealliance/wit-bindgen/blob/749c01697bb3b11daeae4225789e14b765dcf839/tests/runtime/lists/wasm.rs#L1

**Comment by alexcrichton** [comment]
Thanks for the report! I've fixed the README in https://github.com/bytecodealliance/wit-bindgen/pull/652
